# Dependencies
markdown:         kramdown 
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Mingrui YU
tagline:          'HomePage of Mingrui YU'
description:      'HomePage of Mingrui YU'
url:              https://github.com/Mingrui-Yu/Mingrui-Yu.github.io
baseurl:          /

author:
  name:           'Mingrui YU'
  url:            https://mingrui-yu.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
